### ISSUE TITLE
look for `github.user` in .gitconfig

### ISSUE THREAD

**Issue by justinmk** [mmozuras/vim-github-comment#10]
https://github.com/mattn/gist-vim looks for the github user name in one's `.gitconfig` in the custom `[github]` section. 

```
[github]
  user = justinmk
```

The [code for this](https://github.com/mattn/gist-vim/blob/master/autoload/gist.vim#L36-L41) isn't too bad:

```vim
if !exists('g:github_user')
  let g:github_user = substitute(s:system('git config --get github.user'), "\n", '', '')
endif
```

Perhaps vim-github-comment can look for this as an alternative to `g:github_user`, since vim-github-comment is in the "family" of plugins that use @mattn's webapi. It would be nice to see some convergence of configuration conventions in the various Vim "github plugins".

**Comment by sloria** [comment]
+1 to this

**Comment by mmozuras** [comment]
@justinmk @sloria totally makes senses and now is done :smile:

**Comment by justinmk** [comment]
Thanks!
