### ISSUE TITLE
feature: account for two-factor authentication

### ISSUE THREAD

**Issue by mikedfunk** [mmozuras/vim-github-comment#13]
What happens when two-factor authentication is enabled on my account:
![image](https://cloud.githubusercontent.com/assets/661038/25730215/9d539b6a-30ef-11e7-8560-a6a50a9e351c.png)

**Comment by mmozuras** [comment]
I have two-factor authentication enabled too. Just tried to make a comment via `vim-github-comment`, it correctly requested an OTP token. After I've provided an OTP token, a comment was posted.

The relevant code is here: https://github.com/mmozuras/vim-github-comment/blob/master/plugin/github-comment.vim#L160

@mikedfunk I'll need more information to reproduce your issue 🙂. Are you using the latest version of `vim-github-comment`? Did you add `mattn/webapi-vim`? What's the output of `cat ~/.github-comment`?

**Comment by mikedfunk** [comment]
Ah, I got it working. When it asked for the github token I thought it was talking about a Personal Access Token. It was asking for a Two-Factor token so it could create a Personal Access Token. It wasn't clear what token it was asking for.
